"""Add ParkingSnapshot2 table

Revision ID: 792bc5525f00
Revises: ca3ccda66dcd
Create Date: 2025-10-17 14:11:41.808786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792bc5525f00'
down_revision: Union[str, Sequence[str], None] = 'ca3ccda66dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_snapshots_camera2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('available_spaces', sa.Integer(), nullable=False),
    sa.Column('total_spaces', sa.Integer(), nullable=False),
    sa.Column('occupied_spaces', sa.Integer(), nullable=False),
    sa.Column('occupacy_rate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('processing_time_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_snapshots_camera2_id'), 'parking_snapshots_camera2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_snapshots_camera2_id'), table_name='parking_snapshots_camera2')
    op.drop_table('parking_snapshots_camera2')
    # ### end Alembic commands ###
